# Generated by Django 2.0.1 on 2018-02-01 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(11, "There can't be more than eleven form"), django.core.validators.MinValueValidator(1, "There can't be less then first form")])),
                ('index', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=2)),
            ],
        ),
    ]
