# Generated by Django 2.0.1 on 2018-02-22 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(11, "There can't be more than eleven form"), django.core.validators.MinValueValidator(1, "There can't be less then first form")], verbose_name='form')),
                ('index', models.CharField(max_length=1, verbose_name='index')),
                ('index_en_us', models.CharField(max_length=1, null=True, verbose_name='index')),
                ('index_uk', models.CharField(max_length=1, null=True, verbose_name='index')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ('form', 'index'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('form', 'index')},
        ),
    ]
