# Generated by Django 2.0.1 on 2018-02-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20180201_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='index',
            field=models.CharField(max_length=1),
        ),
    ]
