# Generated by Django 2.0.1 on 2018-02-21 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20180201_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='index_en_us',
            field=models.CharField(max_length=1, null=True, verbose_name='index'),
        ),
        migrations.AddField(
            model_name='class',
            name='index_uk',
            field=models.CharField(max_length=1, null=True, verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='class',
            name='form',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(11, "There can't be more than eleven form"), django.core.validators.MinValueValidator(1, "There can't be less then first form")], verbose_name='form'),
        ),
        migrations.AlterField(
            model_name='class',
            name='index',
            field=models.CharField(max_length=1, verbose_name='index'),
        ),
    ]
