# Generated by Django 2.0.1 on 2018-02-22 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='selected_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class', verbose_name='selected class'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='selected_teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher', verbose_name='selected teacher'),
        ),
    ]
