# Generated by Django 2.0.1 on 2018-01-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=80)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('default_classroom', models.SmallIntegerField()),
            ],
        ),
    ]
