# Generated by Django 2.0.1 on 2018-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='second_name_en_us',
            field=models.CharField(max_length=80, null=True, verbose_name='second name'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='second_name_uk',
            field=models.CharField(max_length=80, null=True, verbose_name='second name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='default_classroom',
            field=models.SmallIntegerField(verbose_name='default classroom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_class_teacher',
            field=models.BooleanField(default=False, verbose_name='is class teacher?'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='second_name',
            field=models.CharField(max_length=80, verbose_name='second name'),
        ),
    ]
