# Generated by Django 2.0.1 on 2018-02-22 10:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday')),
                ('lesson_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(8, message="There can't be more than 8 lessons")], verbose_name='lesson number')),
                ('classroom', models.IntegerField(verbose_name='classroom')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.Class', verbose_name='class name')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Lessons', verbose_name='lesson')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'timetable',
                'verbose_name_plural': 'timetables',
                'ordering': ('weekday', 'lesson_number', 'teacher'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('teacher', 'weekday', 'lesson_number')},
        ),
    ]
