# Generated by Django 2.0.1 on 2018-01-09 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thr', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('lesson_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(8, message="There can't be more than 8 lessons")])),
                ('lesson_name', models.CharField(choices=[('CS', 'Computer Science'), ('Tech', 'Technologies')], max_length=4)),
                ('class_name', models.CharField(choices=[('5a', '5-A'), ('5b', '5-B'), ('6a', '6-A'), ('6b', '6-B'), ('7a', '7-A'), ('7b', '7-B'), ('8a', '8-A'), ('8b', '8-B'), ('9a', '9-A'), ('9b', '9-B'), ('10', '10'), ('11', '11')], max_length=3)),
                ('classroom', models.IntegerField()),
            ],
        ),
    ]
