# Generated by Django 2.0.1 on 2018-02-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='by_groups',
            field=models.BooleanField(default=False),
        ),
    ]
