# Generated by Django 2.0.1 on 2018-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_timetable_by_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='by_groups',
            field=models.BooleanField(default=False, verbose_name='by groups'),
        ),
    ]
