# Generated by Django 2.0.1 on 2018-01-30 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20180125_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedteacher',
            name='selected',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
    ]
