# Generated by Django 2.0.1 on 2018-01-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20180131_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedteacher',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
