# Generated by Django 2.0.1 on 2018-02-01 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_selectedteacher_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='classes.Class'),
        ),
    ]
