# Generated by Django 2.0.1 on 2018-02-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20180201_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_name',
            field=models.CharField(choices=[('5a', '5-A'), ('5b', '5-B'), ('6a', '6-A'), ('6b', '6-B'), ('7a', '7-A'), ('7b', '7-B'), ('8a', '8-A'), ('8b', '8-B'), ('9a', '9-A'), ('9b', '9-B'), ('10', '10'), ('11', '11')], max_length=3),
        ),
    ]
