# Generated by Django 2.0.1 on 2018-02-02 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('tables', '0008_auto_20180201_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ('weekday', 'lesson_number', 'teacher'), 'verbose_name': 'timetable', 'verbose_name_plural': 'timetables'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='classes.Class'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('teacher', 'weekday', 'lesson_number')},
        ),
    ]
