# Generated by Django 2.0.1 on 2018-02-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20180202_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='lesson_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='lessons.Lessons'),
        ),
    ]
