# Generated by Django 2.0.1 on 2018-02-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20180202_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='lesson_name',
            new_name='lesson',
        ),
    ]
