# Generated by Django 2.0.1 on 2018-02-21 19:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_auto_20180202_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedteacher',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='is teacher?'),
        ),
        migrations.AlterField(
            model_name='selectedteacher',
            name='selected',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher', verbose_name='selected teacher'),
        ),
        migrations.AlterField(
            model_name='selectedteacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.Class', verbose_name='class name'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classroom',
            field=models.IntegerField(verbose_name='classroom'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Lessons', verbose_name='lesson'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(8, message="There can't be more than 8 lessons")], verbose_name='lesson number'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday'),
        ),
    ]
