# Generated by Django 2.0.1 on 2018-02-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name': 'lesson', 'verbose_name_plural': 'lessons'},
        ),
        migrations.AlterField(
            model_name='lessons',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='short_name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
