# Generated by Django 2.0.1 on 2018-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20180201_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='name_en_us',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='name_uk',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='short_name_en_us',
            field=models.CharField(max_length=5, null=True, unique=True, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='short_name_uk',
            field=models.CharField(max_length=5, null=True, unique=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='short_name',
            field=models.CharField(max_length=5, unique=True, verbose_name='short name'),
        ),
    ]
